[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Flask-Session"
authors = [{name = "Flask-Session", email = ""}]
dynamic = ["version", "description"]
